# Generated by Django 5.2.1 on 2025-10-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_description_account_account_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Receivables', 'Receivables'), ('Payables', 'Payables'), ('Equity Capital', 'Equity Capital')], default='Cash', max_length=100),
        ),
    ]
