# Generated by Django 5.2.1 on 2025-10-29 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, unique=True, verbose_name='Customer Name')),
                ('customer_email', models.EmailField(max_length=254, unique=True, verbose_name='Customer Email')),
                ('customer_phone', models.CharField(max_length=15, unique=True, verbose_name='Customer Phone')),
                ('customer_address', models.TextField(blank=True, null=True, verbose_name='Customer Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='Project Name')),
            ],
        ),
    ]
