# Generated by Django 5.2.1 on 2025-09-24 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('project', '0003_remove_project_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='project_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
