# Generated by Django 5.2.1 on 2025-09-25 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_remove_project_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=255, verbose_name='Contractor Name')),
                ('contractor_phone', models.CharField(max_length=15, unique=True, verbose_name='Contractor Phone')),
                ('contractor_address', models.TextField(blank=True, null=True, verbose_name='Contractor Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='Project Name')),
            ],
        ),
    ]
