# Generated by Django 5.2.1 on 2025-10-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.AddField(
            model_name='profile',
            name='departments',
            field=models.ManyToManyField(blank=True, to='accounts.department'),
        ),
    ]
