# Generated by Django 5.2.1 on 2025-09-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(default='construction', max_length=50),
        ),
    ]
