# Generated by Django 5.2.1 on 2025-09-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='department',
        ),
    ]
